### ISSUE TITLE
[버그] admin > 커뮤니티 관리 > 관리 페이지로 이동 (날짜 값이 빈값으로 보임)

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#110]
![Image](https://github.com/user-attachments/assets/b47687c4-7d63-410e-bc41-947fd6f199ec)

**Comment by seungchan100** [comment]
조회수/다운로드 수는 전체만 나오도록 수정

![Image](https://github.com/user-attachments/assets/866e4db9-42fb-46e9-80aa-728fb0221072)

**Comment by yjhwang93** [comment]
확인했음..고생했오..!
