### ISSUE TITLE
[관리자] 커뮤니티 게임코드 매칭 오류

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#124]
게임코드 매칭 기능 오류
커뮤니티만 안됨

https://www.gamess.co.kr/yjhwang/game_code.php

**Comment by yjhwang93** [comment]
https://admin.gamess.kr/game_code.php
https://admin.gamess.kr/game_code_02.php

두개 파일 수정 확인중

**Comment by yjhwang93** [comment]
관리자 
- https://www.gamess.co.kr/yjhwang/game_code.php

매칭기능 정상작동하지 않음

**Comment by seungchan100** [comment]
게임코드가 없으면 왼쪽에 리스팅하고, 게임코드를 수동으로 입력하게한다.

**Comment by seungchan100** [comment]
신규 디자인 : https://www.gamess.co.kr/yjhwang/game_code_match2.php?data_type=pds_game

**Comment by yjhwang93** [comment]
확인 완료 괜찮아 보임.. 이견 없음 라이브 반영 고고싱.. 실제 써보면서 추가 피드백 예정

**Comment by seungchan100** [comment]
라이브반영했습니다

**Comment by yjhwang93** [comment]
https://www.gamess.co.kr/yjhwang/game_code.php

코드 직접 지정해서 입력 후 리스트에서 사라져야 하는데 사라지지 않음

공략/팁 > 폴아웃2 한글패치 101973 코드값 직접 입력시 입력이 안되는것으로 보임

**Comment by seungchan100** [comment]
재수정하였습니다
