### ISSUE TITLE
[서버] 개발서버 환경 만들기

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#145]
개발서버 환경만들기

dev.gamess.co.kr 에 기존 서버 데이터 업데이트
개발은 dev.gamess.co.kr 에서 진행
개발이 완료되면 www.gamess.co.kr 로 옮기는 형태로 개발 진행

**Comment by yjhwang93** [comment]
(완) 최신화 gamess.co.kr_www 폴도의 자료를 gamess.co.kr_dev 폴더로 이관
(완) 도메인 연결, https://dev.gamess.co.kr 


### 이슈
- dev.gamess.co.kr 에서 로그인이 안됨

**Comment by seungchan100** [comment]
dev.gamess.co.kr 에서 로그인이 안됨
--> 확인해보기

**Comment by seungchan100** [comment]
구글로그인은 테스트용 설정을 따로 해야합니다
그냥 로그인 사용하는것으로..테스트 부탁드립니다.
