### ISSUE TITLE
[개발] 마이페이지 > 나의 GM 현황

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#78]
https://www.gamess.co.kr/gs1.1/my-gm.php
개발하기

**Comment by seungchan100** [comment]
https://bt.gamess.co.kr/gs2.0/my-gm.php

**Comment by seungchan100** [comment]
https://www.gamess.co.kr/my_gm_history2 에 개발완료

**Comment by yjhwang93** [comment]
QA 진행했고 수정사항은 아래건

수정사항
1. 비로그인시 "로그인 후 이용이 가능합니다" 경고창

**Comment by seungchan100** [comment]
반영필요

**Comment by seungchan100** [comment]
반영완료

**Comment by yjhwang93** [comment]
고생했어..!
