### ISSUE TITLE
[개발]  마이페이지 > 나의 다운로드 현황

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#79]
https://www.gamess.co.kr/gs1.1/my-download.php 개발하기

**Comment by seungchan100** [comment]
https://bt.gamess.co.kr/gs2.0/my-download.php

**Comment by seungchan100** [comment]
https://www.gamess.co.kr/my_down_list2 
개발하였습니다.

**Comment by yjhwang93** [comment]
확인했고 이견 없음.. 반영 고고싱!!

**Comment by seungchan100** [comment]
12/11 반영
