### ISSUE TITLE
[QA] 업로드페이지 개편

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#82]
https://www.gamess.co.kr/upload-form

**Comment by seungchan100** [comment]
- 게임변경하기 > 검색버튼 넣는거 하기 
- 게임명 리스트 : 콤보박스 > 리스트 형식으로 표시되게

**Comment by seungchan100** [comment]
가이드 사이트
https://ckeditor.com/docs/ckeditor5/latest/getting-started/index.html

설치는 완료되었으나 이미지가 업로드 되지 않음

찾은 기술문서
https://earscoming.tistory.com/entry/ckEditors5-ckEditors5-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%AA%BB-%EB%B6%88%EB%9F%AC%EC%98%A4%EB%8A%94-%EC%98%A4%EB%A5%98-feat-figure-classimageimgfigure

적용된 페이지
https://www.gamess.co.kr/gs1.1/upload-form.php

**Comment by seungchan100** [comment]
업로드 : https://gamess.co.kr/upload_main2.php?type=board_free
수정 : https://gamess.co.kr/upload_main2.php?mode=modify&type=pds_game&no=20502

공통 
- 게임홈으로 이동

자료등록
- 게임명 변경 
- 제목/내용/내용에 이미지 삽입/첨부파일
- 로그인할때만 등록가능한지?

자료업데이트 
- 게임명 변경 불가 
- 게시판 변경불가
- 첨부파일 변경불가
- 제목 변경되는지? (board / 게임자료)
- 내용 변경되는지? (board / 게임자료)
- 다른사람꺼 수정못하는지?

**Comment by seungchan100** [comment]
10/30 교체완료.
