### ISSUE TITLE
[개발] 게임리스트 페이지 개편

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs2.0-Renewal#83]
https://www.gamess.co.kr/game_list.php?class=all&p=1&sort=data_count-desc#google_vignette

이화면에 대한 퍼블리싱

**Comment by seungchan100** [comment]
게임 정보 변경은 관리자만 가능하도록

**Comment by seungchan100** [comment]
정보수정과 게임등록하는 부분은 관리자페이지에서만 하는것으로 할 수 있을까요?
(기능 복잡)

**Comment by yjhwang93** [comment]
이견 없음 관리자에서만 수정 & 등록 가능하도록

**Comment by seungchan100** [comment]
https://www.gamess.co.kr/game_list2.php?class=all&p=1&sort=data_count-desc
개발완료. 

근데 등록일이 이상하게 되어 있는 게임들이 많은데, 
이상하게 되어 있는애들 다 2000-01-01 쯤으로 일괄 변경해볼까요?

![Image](https://github.com/user-attachments/assets/1c23afc3-706d-4fc3-b191-48dd41f6d8e4)

**Comment by yjhwang93** [comment]
그러네.. 그 쯤으로 일괄 변경하는게 좋을듯함..

**Comment by yjhwang93** [comment]
간단히 QA 해봤는데 특별한 기능이 없어서 바로 라이브에 배포해도 될듯함

**Comment by seungchan100** [comment]
아래 대상으로 등록일을 ' 2000-01-01'로 변경하였고, 라이브 배포하였습니다.
game_date = '1970-01-01';
game_date = '0000-00-00';
game_date is null;



MariaDB [gamess_renewal]> update game_info set game_date = '2000-01-01' where game_date = '1970-01-01';
Query OK, 78 rows affected (0.01 sec)
Rows matched: 78  Changed: 78  Warnings: 0

MariaDB [gamess_renewal]> update game_info set game_date = '2000-01-01' where game_date = '0000-00-00';
Query OK, 1395 rows affected (0.02 sec)
Rows matched: 1395  Changed: 1395  Warnings: 0

MariaDB [gamess_renewal]> update game_info set game_date = '2000-01-01' where game_date is null;
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

**Comment by seungchan100** [comment]
game_info 복구후 game_date 업데이트까지 완료했습니다~
board랑 pds_game 테이블도 복구하였습니다.

**Comment by yjhwang93** [comment]
고생했어...
